pr:
  branches:
    include: [main]

  paths:
    include:
      - eng/pipelines/checks.yml

trigger:
  branches:
    include: [main]

jobs:
  - job: PoliCheck
    pool:
      name: azsdk-pool-mms-win-2022-general
      vmImage: windows-2022
    timeoutInMinutes: 120
    steps:
      - template: /eng/common/pipelines/templates/steps/policheck.yml
        parameters:
          ExclusionDataBaseFileName: AwesomeAzdPoliCheckExclusion
          PublishAnalysisLogs: false

  - job: CGScan
    pool:
      name: azsdk-pool-mms-win-2022-general
      vmImage: windows-2022

    variables:
      CLI_VERSION: 1.0.0-alpha.1

    steps:
      - checkout: self

      - pwsh: npm install && npm run build
        workingDirectory: website/
        displayName: Build site

      - task: ComponentGovernanceComponentDetection@0

  - job: GenerateNoticeTxt
    pool:
      name: azsdk-pool-mms-ubuntu-2004-general
      OSVmImage: MMSUbuntu20.04

    steps:
      - task: ComponentGovernanceComponentDetection@0

      - task: notice@0
        displayName: Generate NOTICE.txt file
        inputs:
          outputfile: $(Build.SourcesDirectory)/NOTICE.txt
          outputformat: text

      - publish: NOTICE.txt
        artifact: notice
