
trigger:
  branches:
    include:
      - main

jobs:
  - job: build_and_commit
    displayName: Build and Commit
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - checkout: self
        persistCredentials: false

      - script: |
          npm ci
          npm run build
        workingDirectory: website/
        displayName: 'Build Website'

      - script: |
          set -e
          AUTH_HEADER="AUTHORIZATION: bearer $GH_PAT"
          export GIT_CONFIG_GLOBAL=/dev/null
          mkdir daily-fork
          cd daily-fork
          git init
          git remote add origin "https://github.com/azure-sdk/awesome-azd.git"
          git -c http.extraheader="$AUTH_HEADER" fetch --no-tags origin gh-pages
          git checkout gh-pages
          cp -R ../website/build/* .
          git add .
          git -c user.name="azure-sdk" -c user.email="azuresdk@microsoft.com" commit -a -m "daily release"
          git -c http.extraheader="$AUTH_HEADER" push --quiet origin gh-pages
        env:
          GH_PAT: $(azuresdk-github-pat)
        displayName: 'Commit to Azure SDK Fork'
