
trigger:
  branches:
    include:
      - main

jobs:
  - job: build_and_commit
    displayName: Build and Commit
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - checkout: self

      - script: |
          npm install
          npm run build
        workingDirectory: website/
        displayName: 'Build Website'

      - script: |
          git config --global user.email "azuresdk@microsoft.com"
          git config --global user.name "azure-sdk"
          mkdir daily-fork
          cd daily-fork
          git init
          # git remote add Source "https://$($AuthToken)@github.com/azure-sdk/awesome-azd.git"
          git remote add Source "https://github.com/azure-sdk/awesome-azd.git"
          git fetch --no-tags Source gh-pages
          git checkout gh-pages
          cp -R ../website/build/* .
          git add .
          git commit -a -m "daily release"
          git push origin gh-pages
        displayName: 'Commit to Azure SDK Fork'
