name: Release Awesome Azd

# This pipeline is manually started only as part of releasing Awesome AZD
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pages: write
  deployments: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  sync:
    name: Sync Main to GH-Pages
    uses: ./.github/workflows/sync-gh-pages.yml
    permissions:
      contents: write

  deploy:
    name: Deploy Site To GitHub Pages
    needs: sync
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6
        with:
          ref: ${{ needs.sync.outputs.synced_sha }}
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f  # v6
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: website/package-lock.json
      - name: Build website
        working-directory: website
        run: |
          npm ci
          npm run build
      - name: Test
        working-directory: website
        run: |
          npm test
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b  # v4
        with:
          path: ./website/build
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e  # v4