name: Release Awesome Azd

# This pipeline is manually started only as part of releasing Awesome AZD
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pages: write
  deployments: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy Site To GitHub Pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: website/package-lock.json
      - name: Build website
        working-directory: website
        run: |
          npm ci
          npm run build
      - name: Test
        working-directory: website
        run: |
          npm test
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./website/build
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4