name: Test Deploy (on PR)

on:
  pull_request:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

permissions:
  contents: read

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f  # v6
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: website/package-lock.json
      - name: Build website
        working-directory: website
        run: |
          npm ci
          npm run build
      - name: Run Tests
        working-directory: website
        run: |
          npm test